version: '2.0'
services:
  #rocketchat:
  #  image: "rocket.chat:0.70.4"
  #  volumes:
  #    - ./app:/app:rw
  #  depends_on:
  #    - db
  #  ports:
  #    - "3000:3000"
  #  restart: always
  db:
    image: "mongo:3.0"
    ports:
      - "27017:27017"

